<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 29.12.2016
 * Time: 12:13
 */
?>
<div class="container last">

    <!-- index.php -->


    <div class="row">

        <div class="small-12 columns">
            <article class="post-58 page type-page status-publish hentry">
                <h1>Terms of Service</h1>


                <p>PLEASE READ THE FOLLOWING TERMS OF USE AGREEMENT CAREFULLY. BY ACCESSING OR USING OUR SITES AND OUR SERVICES, YOU HEREBY AGREE TO BE BOUND BY THE TERMS AND ALL TERMS INCORPORATED HERIN BY REFERENCE. IF YOU DO NOT EXPRESSLY AGREE TO ALL OF THE TERMS AND CONDITIONS, THEN PLEASE DO NOT ACCESS OR USE OUR SITES OR OUR SERVICES. THIS TERMS OF SERVICE AGREEMENT IS EFFECTIVE AS OF 12/08/2014</p>
                <p>&nbsp;</p>
                <p><strong>ACCEPTANCE OF TERMS</strong></p>
                <p>The following Terms of Service Agreement (“the “TOS”) is a legally binding agreement that shall govern the relationship with our users and others which may interact or interface with First American Service Group, Inc., also known as STDAware.com, located at 6149 S Rainbow Blvd, Las Vegas, Nevada 89118, and our subsidiaries and affiliates, in association with the use of the STDAware.com website, which includes https://www.stdaware.com/ (the “Site”) and its Services, which shall be defined below.</p>
                <p>&nbsp;</p>
                <p><strong>DESCRIPTION OF WEBSITE SERVICES OFFERED</strong></p>
                <p>The Site is an e-commerce website which has the following description.</p>
                <p>STDAware.com will test you for one or more sexually transmitted diseases as indicated on the order form, as authorized by a physician where necessary, in accordance with all state and federal laws (“Order”).</p>
                <p>Testing for sexually transmitted disease will be performed at an independent clinical laboratory location (“Lab”) in accordance with any Order issued by a physician on behalf of First American Service Group, Inc.</p>
                <p>First American Service Group, Inc. will provide the results of your testing along with educational information by telephone, e-mail, or other means.</p>
                <p>Any and all visitors to our site, despite whether they are registered or not, shall be deemed as “users” of the herein contained Services provided for the purpose of this TOS. Once an individual registers for our Services, through the process of creating an account, the user shall then be considered a “member.”</p>
                <p>&nbsp;</p>
                <p>The user and/or member acknowledges and agrees that the Services provided and made available through our website and applications, which may include some mobile applications, are the sole property of First American Service Group, Inc. At its discretion, Frist American Service Group, Inc. may offer additional website Services and/or products, or update, modify or revise any current content and Services, and this Agreement shall apply to any and all additional Services and/or products and any and all updated, modified, or revised Services unless otherwise stipulated. First American Service Group, Inc. does herby reserve the right to cancel and cease offering any of the aforementioned Services and/or products. You, as the end user and/or member, acknowledge, accept, and agree that First American Service Group, Inc. shall not be held liable for any such updates, modifications, revisions, suspensions, or discontinuance of any of our Services and/or products. Your continued use of the Services provided, after such posting of any updates, changes, and/or modifications shall constitute your acceptance of such updates, changes, and/or modifications, and as such, frequent review of this Agreement and any and all applicable terms and policies should be made by you to ensure you are aware of all terms and policies currently in effect. Should you not agree to the updated, modified, revised, or modified terms, you must stop using the provided Services.</p>
                <p>Furthermore, the user and/or member understands, acknowledges and agrees that the Services offered shall be provided “AS IS” and as such First American Service Group, Inc. shall not assume any responsibility or obligation for the timeliness, missed delivery, deletion, and/or any failure to store user content, communication or personalization settings.</p>
                <p><strong> Order Policy &#8211; Payment of Fees and/or Cancellation</strong></p>
                <p><em>Refund Policy</em> &#8211; Any test not fulfilled within 90 days will require a new order and laboratory authorization and no refunds will be provided.<br />
                    You may cancel or change your lab order at any time prior to (i) your visit to the lab, or (ii) 21 days after accepting this agreement for a full refund.</p>
                <p><em>Payment Types &#8211; </em>First American Service Group, Inc. accepts electronic payment in the form of credit or debit card, pre-paid cards such as gift cards or health-savings accounts. First American Service Group, Inc. does not accept health insurance as a method of payment.</p>
                <p><strong>REGISTRATION</strong></p>
                <p>To register and become a “member” of the Site, you must be 18 years of age to enter into and form a legally binding contract. In addition, you must be in good standing and not an individual that has been previously barred from receiving STDAware.com’s Services under the laws and statutes of the United States or other applicable jurisdiction.</p>
                <p>Furthermore, the registering party hereby acknowledges, understands, and agrees to:</p>
                <p>a)      Furnish factual, correct, current and complete information with regards to yourself as may be requested by the data registration process, and</p>
                <p>b)      Maintain and promptly update your registration and profile information in an effort to maintain accuracy and completeness at all times.</p>
                <p>If anyone knowingly provides any information of a false, untrue, inaccurate, or incomplete nature, First American Service Group, Inc. will have sufficient grounds and rights to suspend or terminate the member in violation of this aspect of the Agreement, and as such refuse any and all current or future use of First American Service Group, Inc. Services or any portion thereof.</p>
                <p><strong>PRIVACY POLICY</strong></p>
                <p>Every member’s registration data and various other personal information are strictly protected by the First American Service Group, Inc. Online Privacy Policy (see the full Privacy Policy at https://www.stdaware.com/privacy-policy). As a member, you herin consent to the collection and use of the information provided, including the transfer of information within the United States and/or other countries for storage, processing or use by First American Service Group, Inc. and/or our subsidiaries and affiliates.</p>
                <p>&nbsp;</p>
                <p><strong>MEMBER ACCOUNT, USERNAME, PASSWORD AND SECURITY</strong></p>
                <p>After completion of the registration data and creation of your username, you will select a password and account designation. You shall be responsible for maintaining the secrecy and confidentiality of your password and for all activities that transpire within your account. It shall be your responsibility to notify First American Service Group, Inc. immediately if you notice any unauthorized access or use of your account or password or any other breach of security. First American Service Group, Inc. shall not be held liable for any loss and/or damage arising from any failure to comply with this term and/or condition of the TOS.</p>
                <p><strong>CONDUCT</strong><br />
                    As a member of the Site, you herein acknowledge, understand and agree that all information, text, software, data, photographs, music, video. messages, tags or any other content, whether it is publicly or privately posted and/or transmitted, is the expressed sole responsibility of the individual from whom the content originated, In short, this means that you are solely responsible for any and all content posted, uploaded, emailed, transmitted or otherwise made available by way of STDAware.com Services, and as such, we do not guarantee the accuracy, integrity or quality of such content It is expressly understood that by use of our Services, you may be exposed to content including, but not limited to, any errors or omissions in any content posted, and! or any loss or damage of any kind incurred as a result of the use of any content posted, emailed, transmitted or otherwise made available by STDAware.com.<br />
                    Furthermore, you herein agree not to make use of First American Service Group, Inc.’s Services for the purpose of<br />
                    a) uploading, posting, emailing, transmitting, or otherwise making available any content that shall be deemed unlawful, harmful, threatening, abusive, harassing, tortious, defamatory. vulgar, obscene. libelous, or invasive of another’s privacy or which is hateful. And/or racially, ethnically, or otherwise objectionable;<br />
                    b) causing harm to minors in any manner whatsoever;<br />
                    c) impersonating any individual or entity, including, but not limited to, any STDAware.com officials, forum leaders, guides or hosts or falsely stating or otherwise misrepresenting any affiliation with an individual or entity;<br />
                    d) forging captions, headings or titles or otherwise offering any content that you personally have no right to pursuant to any law nor having any contractual or fiduciary relationship with;<br />
                    e) uploading, posting, emailing, transmitting or otherwise offering any such content that may infringe upon any patent, copyright, trademark, or any other proprietary or intellectual rights of any other party;<br />
                    f) uploading, posting, emailing, transmitting or otherwise offering any content that you do not personally have any right to offer pursuant to any law or in accordance with any contractual or fiduciary relationship;<br />
                    g) uploading, posting, emailing, transmitting, or otherwise offering any unsolicited or unauthorized advertising, promotional flyers, “junk mail” “spam” or any other form of solicitation, except in any such areas that may have been designated for such purpose;<br />
                    h) uploading, posting, emailing, transmitting, or otherwise offering any source that may contain a software virus or other computer code, any files and/or programs which have been designed to interfere, destroy and or limit the operation of any computer software, hardware, or telecommunication equipment;<br />
                    E) disrupting the normal flow of communication, or otherwise acting in any manner that would negatively affect other users’ ability to participate in any real time interactions;<br />
                    f) interfering with or disrupting any First American Service Group, Inc. Services, servers and/or networks that may be connected or related to our website, including, but not limited to, the use of any device software and or routine to bypass the robot exclusion headers;<br />
                    k) intentionally or unintentionally violating any local, state, federal, national or international law, including, but not limited to: rules, guidelines, and or regulations decreed by the U.S. Securities and Exchange Commission, in addition to any rules of any nation or other securities exchange, that would include without limitation, the New York Stock Exchange,<br />
                    the American Stock Exchange, or the NASDAQ, and any regulations having the force of law;<br />
                    1) providing informational support or resources, concealing and or disguising the character, location, and or source to any organization delegated by the United States government as a “foreign terrorist organization” in accordance to Section 219 of the Inmigration Nationality Act;<br />
                    m) “stalking” or with the intent to otherwise harass another individual; and or</p>
                <p>n) collecting or storing of any personal data relating to any other member or user in connection with the prohibited conduct and: or activities which have been set forth in the aforementioned paragraphs First American Service Group. Inc. herein reserves the right to pre-screen, refuse and or delete any content currently available through our Services In addition, we reserve the right to remove and/or delete any such content that would violate the TOS or which would otherwise be considered offensive to other visitors, users and/or members First American Service Group, Inc. herein reserves the right to access: preserve and or disclose member account information and/or content if it is requested to do so by law or in good faith belief that any such action is deemed reasonably necessary for<br />
                    a) compliance with any legal process;<br />
                    b) enforcement of the TOS;<br />
                    c) responding to any claim that therein contained content is in violation of the rights of any third party;</p>
                <p>d) responding to requests for customer service; or<br />
                    e) protecting the rights, property or the personal safety of First American Service Group. Inc.. its visitors, users and members, including the general public.<br />
                    First American Service Group, Inc. herein reserves the right to include the use of security components that may permit digital information or material to be protected, and that such use of information and/or material is subject to usage guidelines and regulations established by First American Service Group, Inc. or any other content providers supplying content services to First American Service Group, Inc.. You are hereby prohibited from making any attempt to override or circumvent any of the embedded usage rules in our Services. Furthermore, unauthorized reproduction, publication, distribution, or exhibition of any information or materials supplied by our Services, despite whether done so in whole or in part, is expressly prohibited.</p>
                <p><strong>INDEMNITY</strong><br />
                    All users and/or members herein agree to insure and hold First American Service Group, Inc., our subsidiaries, affiliates, agents, employees, officers, partners and/or licensors blameless or not liable for any claim or demand, which may include, but is not limited to: reasonable attorney fees made by any third party, which may arise from any content a member or user of our site may submit, post, modify, transmit or otherwise make available through our Services, the use of STDAware.com Services or your connection with these Services, your violations of the Terms of Service and/or your violation of any such rights of another person.<br />
                    <strong>COMMERCIAL REUSE OF SERVICES</strong><br />
                    The member or user herein agrees not to replicate, duplicate, copy, trade: sell: resell nor exploit for any commercial reason any part, use of, or access to STDAware.com’s sites.<br />
                    <strong>USE AND STORAGE GENERAL PRACTICES</strong><br />
                    You herein acknowledge that First American Service Group: Inc. may set up any such practices and/or limits regarding the use of our Services, without limitation of the maximum number of days that any email, message posting or any other uploaded content shall be retained by First American Service Group, hic., nor the maximum number of email messages that may be sent and or received by any member, the maximum volume or size of any email message that may be sent from or may be received by an account on our Service, the maximum disk space allowable that shall be allocated on First American Service Group, Inc.’s servers on the member’s behalf and/or the maximum number of times and or duration that any member may access our Services in a given period of time. In addition, you also agree that First American Service Group, Inc. has absolutely no responsibility or liability for the removal or failure to maintain storage of any messages and or other communications or content maintained or transmitted by our Services You also herein acknowledge that we reserve the right to delete or remove any account that is no longer active for an extended period of time. Furthermore, First American Service Group, Inc. shall reserve the right to modify, alter and or update these general practices and limits at our discretion.<br />
                    <strong>MODIFICATIONS</strong><br />
                    First American Service Group, Inc. shall reserve the right at any time it may deem fit, to modify, alter and or discontinue, whether temporarily or permanently, our service, or any part thereof, with or without prior notice- In addition, we shall not be held liable to you or to any third party for any such alteration, modification, suspension and/or discontinuance of our Services, or any part thereof<br />
                    <strong>TERMINATION</strong><br />
                    As a member of https://www.stdaware.com/, you may cancel or terminate your account, associated email address and or access to our Services by submitting a cancellation or termination request to <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="92e1e7e2e2fde0e6d2e1e6f6f3e5f3e0f7bcf1fdffbc">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script><br />
                    As a member, you agree that First American Service Group, Inc. may, without any prior written notice, immediately suspend, terminate, discontinue and/or limit your account, any email associated with your account, and access to any of our Service. The cause for such termination, discontinuance, suspension and/or limitation of access shall include, but is not limited to:<br />
                    a) any breach or violation of our TOS or any other incorporated agreement regulation and/or guideline;<br />
                    b) by way of requests from law enforcement or any other governmental agencies;<br />
                    c) the discontinuance, alteration and/or material modification to our Services, or any part thereof<br />
                    d) unexpected technical or security issues and/or problems;<br />
                    e) any extended periods of inactivity;<br />
                    f) any engagement by you in any fraudulent or illegal activities; and/or<br />
                    g) the nonpayment of any associated fees that may be owed by you in connection with your https://www.stdaware.com/ account Services.<br />
                    Furthermore. you herein agree that any and all terminations, suspensions, discontinuances, and or limitations of access for cause shall be made at our sole discretion and that we shall not be liable to you or any other third party with regards to the termination of your account, associated email address and/or access to any of our Services.<br />
                    The termination of your account with https://www.stdaware.com shall include any and/or all of the following:<br />
                    a) the removal of any access to all or part of the Services offered within https://www.stdaware.com/;<br />
                    b) the deletion of your password and any and all related information, files, and any such content that may be associated with or inside your account, or any part thereof; and<br />
                    c) the barring of any further use of all or part of our Services.<br />
                    <strong>ADVERTISERS</strong><br />
                    Any correspondence or business dealings with, or the participation in any promotions of: advertisers located on or through our Services, which may include the payment and/or delivery of such related goods and/or Services, and any such other term, condition, warranty and/or representation associated with such dealings, are and shall be solely between you and any such advertiser. Moreover, you herein agree that First American Service Group, Inc. shall not be held responsible or liable for any loss or damage of any nature or manner incurred as a direct result of any such dealings or as a result of the presence of such advertisers on our website<br />
                    <strong>LINKS</strong><br />
                    Either First American Service Group. Inc or any third parties may provide links to other websites and/or resources. Thus, you acknowledge and agree that we are not responsible for the availability of any such external sites or resources, and as such, we do not endorse nor are we responsible or liable for any content, products, advertising or any other materials, on or available from such third party sites or resources. Furthermore, you acknowledge and agree that First American Service Group, Inc. shall not be responsible or liable, directly or indirectly, for any such damage or loss which may be a result of, caused or alleged to be caused by or in connection with the use of or the reliance on any such content, goods, or Services made available on or through any such site or resource.</p>
                <p><strong>PROPRIETARY RIGHTS</strong><br />
                    You do hereby acknowledge and agree that First American Service Group, Inc.’s Services and any essential software that may be used in connection with our Services (“Software”) shall contain proprietary and confidential material that is protected by applicable intellectual property rights and other laws. Furthermore, you herein acknowledge and agree that any Content which may be contained in any advertisements or information presented by and through our Services or by advertisers is protected by copyrights, trademarks, patents or other proprietary rights and laws. Therefore, except for that which is expressly permitted by applicable law or as authorized by First American Service Group, Inc. or such applicable licensor, you agree not to alter. modify. lease, rent, loan, sell, distribute, transmit, broadcast, publicly perform and or created any plagiaristic works which are based on First American Service Group, Inc. Services (e.g. Content or Software), in whole or part.<br />
                    First American Service Group, Inc. herein has granted you personal, non-transferable and non-exclusive rights and/or license to make use of the object code or our Software on a single computer, as long as you do not, and shall not, allow any third party to duplicate, alter, modify, create or plagiarize work from, reverse engineer, reverse assemble or otherwise make an attempt to locate or discern any source code, sell, assign, sublicense, grant a security interest in and/or otherwise transfer any such right in the Software. Furthermore, you do herein agree not to alter or change the Software in any manner, nature or form, and as such, not to use any modified versions of the Software, including and without limitation, for the purpose of obtaining unauthorized access to our Services. Lastly, you also agree not to access or attempt to access our Services through any means other than through the interface which is provided by First American Service Group, Inc. for use in accessing our Services.</p>
                <p><strong>WARRANTY DISCLAIMERS</strong><br />
                    YOU HEREIN EXPRESSLY ACKNOWLEDGE AND AGREE THAT:<br />
                    a) THE USE OF FIRST AMERICAN SERVICE GROUP, INC. SERVICES AND SOFTWARE ARE AT THE SOLE RISK BY YOU. OUR SERVICES AND SOFTWARE SHALL BE PRO VIDED ON AN “AS IS” AND OR “AS AVAILABLE” BASIS. FIRST AMERICAN SERVICE GROUP. INC. AND OUR SUBSIDIARIES, AFFILIATES, OFFICERS; EMPLOYEES, AGENTS, PARTNERS AN) LICENSORS EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES OF ANY KIND WHETHER EXPRESSED OR IMPLIED. INCLUDING. BUT NOT LIMITED TO ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.<br />
                    b) FIRST AMERICAN SERVICE GROUP: INC. AND OUR SUBSIDIARIES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICESNSORS MAKE NO SUCH WARRANTIES THAT (i) FIRST AMERICAN SERVICE GROUP. INC. SERVICES OR SOFTWARE WILL MEET YOUR REQUIREMENTS; (ii) FIRST AMERICAN SERVICE GROUP, INC. SERVICES OR SOFTWARE SHALL BE UNINTERRUPTED. TIMELY, SECURE OR ERROR-FREE; (iii) THAT SUCH RESULTS WHICH MAY BE OBTAINED FROM THE USE OF THE FIRST AMERICAN SERVICE GROUP, INC. SERVICES OR SOFTWARE WILL BE ACCURATE OR RELIABLE; (iv) QUALITY OF ANY PRODUCTS, SERVICES, ANY INFORMATION OR OTHER MATERIAL WHICH MAY BE PURCHASED OR OBTAINED BY YOU THROUGH OUR SERVICES OR SOFTWARE WILL MEET YOUR EXPECTATIONS; AND (v) THAT ANY SUCH ERRORS CONTAINED IN THE SOFTWARE SHALL BE CORRECTED.</p>
                <p>c) ANY INFORMATION OR MATERIAL DOWNLOADED OR OTHERWISE OBTAIN BY WAY OF FIRST AMERICAN SERVICE GROUP: INC. SERVICES OR SOFTWARE SHALL BE ACCESSED BY YOUR SOLE DISCRETION AND SOLE RISK, AND AS SUCH YOU SHALL BE SOLELY RESPONSIBLE FOR AND HEREBY WAIVE ANY AND ALL CLAIMS AND CAUSES OF ACTION WITH RESPECT TO ANY DAMAGE TO YOUR COMPUTER ANDOR INTERNET ACCESS, DOWNLOADING AND/OR DISPLAYING, OR FOR ANY LOSS OF DATA THAT COULD RESULT FROM THE DOWNLOAD OF ANY SUCH INFORMATION OR MATERIAL.<br />
                    d) NO ADVICE AND/OR INFORMATION, DESPITE WHETHER WRITTEN OR ORAL, THAT MAY BE<br />
                    OBTAINED BY YOU FROM FIRST AMERICAN SERVICE GROUP, INC. OR BY WAY OF OR FROM<br />
                    OUR SERVICES OR SOFTWARE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TOS.<br />
                    <strong>LIMITATION OF LIABILITY</strong></p>
                <p>YOU EXPLICITY ACKNOWLEDGE, UNDERSTAND AND AGREE THAT FIRST AMERICAN SERVICE GROUP, INC. AND OUR SUBISDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS SHALL NOT BE LIABLE TO YOU FOR ANY PUNITIVE, INDIRECT. INCIDENTIAL, SPECIAL, CONSEQUENIAL OR EXEMPLARY DAMAGES, INCLUDING. BUT NOT LIMITED TO, DAMAGES WHICH MAY BE RELATED TO THE LOSS OF ANY PROFITS, GOODWILL, USE, DATA ANDOR OTHER INTANGBLE LOSSES, EVEN THOUGH WE MAY HAVE BEEN ADVISED OF SUCH POSSIBILITY THAT SAID DAMAGES MAY OCCUR, AND RESULT FROM:<br />
                    a) THE USE OR INABILITY TO USE OUR SERVICE;</p>
                <p>b) THE COST OF PRECURING SUBSTITUTE GOODS AND SERVICES:<br />
                    c) UNAUTHORIZED ACCESS TO OR THE ALTERATION OF YOUR TRANSMISSIONS AND OR DATA;<br />
                    d) STATEMENTS OR CONDUCT OF ANY SUCH THRID PARTY ON OUR SERVICE:<br />
                    e) AND ANY OTHER MATTER WHICH MAY BE RELATED TO OUR SERVICE</p>
                <p><strong>EXCLUSION AND LIMITATIONS</strong><br />
                    THERE ARE SOME JURISDICTIONS WHICH DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OF EXCLUSION OF LAIBILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. THEREFORE, SOME OF THE ABOVE LIMITATIONS OF SECTIONS WARRANTY DISCLAIMERS AND LIMITATION OF LIABILITY MAY NOT APPLY TO YOU.<br />
                    <strong>THIRD PARTY BENEFICIARIES</strong><br />
                    You herein acknowledge, understand and agree, unless otherwise expressly provided in this TOS, that there shall be third party beneficiaries to this agreement.<br />
                    <strong>NOTICE</strong><br />
                    First American Service Group, Inc. may furnish you with notices, including those with regards to any changes to the TOS, including but not limited to email, regular mail, MMS or SMS, text messaging, postings on oun website Services, or other reasonable means currently known or any which may be herein after developed. An;’ such notices may not be received if you violate any aspects of the TOS by accessing our Services in an unauthorized manner. Your acceptance of this TOS constitutes your agreement that you are deemed to have received any and all notices that would have been delivered had you accessed our Services in an authorized manner.</p>
                <p><strong>TRADEMARK INFORMATION</strong><br />
                    You herein acknowledge, understand and agree that all of the First American Service Group, Inc. trademarks, copyright, trade name, service marks, and other First American Service Group, Inc. logos and any brand features, and/or product and service names are trademarks and as such, are and shall remain the property of First American Service Group, Inc.. You herin agree not to display and/or use in any manner the First American Service Group, Inc. logo or marks.</p>
                <p><strong>GENERAL INFORMATION</strong><br />
                    <strong>ENTIRE AGREEMENT</strong><br />
                    This TOS constitutes the entire agreement between you and First American Service Group, Inc and shall govern the use of our Services, superseding any prior version of this TOS between you and us with respect to First American Service Group, Inc. Services. You may also be subject to additional terms and conditions that may apply when you use or purchase certain other First American Service Group, Inc Services, affiliate Services, third-party content or third-party software.<br />
                    <strong>CHOICE OF LAW AND FORUM</strong><br />
                    It is at the mutual agreement of both you and First American Service Group, Inc. with regard to the TOS that the relationship between the parties shall be governed by the laws of the state of Nevada without regard to its conflict of law provisions and that any and all claims, causes of action and/or disputes, arising out of or relating to the TOS, or the relationship between you and First American Service Group, Inc. shall be filed within the courts having jurisdiction within the County of Clark, Nevada or the U.S. District Court located in said state You and First American Service Group, Inc. agree to submit to the jurisdiction of the courts as previously mentioned, and agree to waive any and all objections to the exercise of jurisdiction over the parties by such courts and to venue in such courts.<br />
                    <strong>WAIVER AND SEVERABILITY OF TERMS</strong><br />
                    At any time, should First American Service Group, Inc fail to exercise or enforce any right or provision of the TOS, such failure shall not constitute a waiver of such right or provision. If any provision of this TOS is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties intentions as reflected in the provision, and the other provisions of the TOS remain in full force and effect.</p>
                <p><strong>NO RIGHT OF SURVIVORSHIP NON-TRANSFERABILITY</strong><br />
                    You acknowledge, understand and agree that your account is non-transferable and any rights to your ID and or contents within your account shall terminate upon your death. Upon receipt of a copy of a death certificate, your account may be terminated and ail contents therein permanently deleted.<br />
                    <strong>STATUTE OF LIMITATIONS</strong><br />
                    You acknowledge, understand and agree that regardless of any statute or law to the contrary, any claim or action arising out of or related to the use of our Services or the TOS must be filed within 1 year(s) after said claim or cause of action arose or shall be forever barred.<br />
                    <strong>VIOLATIONS</strong><br />
                    Please report any and all violations of this TOS to First American Service Group, Inc. as follows:<br />
                    Mailing Address:<br />
                    First American Service Group, Inc.<br />
                    Attn: Copyright Agent<br />
                    6149 S Rainbow Blvd<br />
                    Las Vegas, NV 89118</p>
                <p>Email: mail@email.com</a><br />
                    Telephone: 855-588-6958</p>


            </article>
        </div>
    </div>
